project:
  type: website

website:
  title: "UoM Prediction Modelling and Causal Inference Group Handbook"
  sidebar:
    style: "floating"
    search: true
    contents:
      - text: "Home"
        file: index.qmd
      - text: "Lab Culture & Working Environment"
        file: lab_culture.qmd
      - text: "Resources & Training"
        file: resources.qmd
      - text: "Data & HPC"
        file: computing.qmd
      - text: "Coding & Reproducible Research"
        file: code_reprod.qmd
      - text: "Publications & Dissemination"
        file: pubs_confs.qmd
      - text: "Funding"
        file: funding.qmd


      
      

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

